### ISSUE TITLE
Hangs on pasting network mounted paths

### ISSUE THREAD

**Issue by jay-ramani** [horeah/PyCmd#22] opened 2024-10-25 00:28 UTC
Mount any network share and either paste a path on it, or try auto-completing. The console instantly hangs!

PyCmd version: 20240904-x64 (happening on at least four versions prior as well, not sure about ones older)
OS version: Windows 11 23H2 build 22631.4317

**Comment by horeah** [comment] 2024-10-25 13:51
Hi, thanks for reporting this!
Is it hanging indefinitely? i.e. still blocked after waiting for, say, 2 minutes? or is this "just" trying to auto-complete on a very slow filesystem? (this is a real problem, that I am currently trying to address by adding a timeout to the auto-completion)

**Comment by jay-ramani** [comment] 2024-10-26 19:00
Hi, thanks for the quick response. Yes, seems to "hang" indefinitely. I have network shares on a Synology DS920+ mounted as drives, and regardless of the mount, the auto-completion seems blocked. The NAS is otherwise accessible from a regular Windows native command line; works instantly, and perfectly fine even with auto-completion. Try it yourself on any network share mounted with PyCmd.
   
I didn't check the code, but in the worst case, do you want to timeout in case you're doing a blocked wait?

**Comment by horeah** [comment] 2024-10-26 20:19
I am using network shares (mounted as drives) with PyCmd without getting into hangs -- but typing can be annoying sometimes due to laggy auto-suggest and/or completion. I'm not sure what is different in your case; here are some questions that might give us some clues (if you can spare some time):
1. did this ever work for you to use PyCmd with network shares? (e.g. a long while ago, with some old version of PyCmd and/or Windows)?
2. what happens if you start PyCmd in a regular folder, then try to type some command that includes a path under X: (say, `dir X:\somedir`)?
3. what happens if you start cmd.exe, cd to X:\somedir, then start PyCmd.exe straight from the command prompt?
4. what happens if you start some python3 interpreter, then `os.chdir('X:\somedir')`, then try to do a `pathlib.Path().glob('*')`?

The timeout feature would help with the typing hiccups that I mentioned above; it could also get over the hangs you are seeing -- but then I would expect that the next thing breaks (completing with Tab, running a command, detecting the current directory etc.)

**Comment by jay-ramani** [comment] 2024-10-27 17:39
I would be very happy to help to have this resolved.

> 1. did this ever work for you to use PyCmd with network shares? (e.g. a long while ago, with some old version of PyCmd and/or Windows)?

No

> 2. what happens if you start PyCmd in a regular folder, then try to type some command that includes a path under X: (say, dir X:\somedir)?

Tries to auto-complete (as in, shows the directory on auto-completion with tab) and hangs. If I don't use auto-completion, as in, directly type a path under the network mounted share, say X:\English, PyCmd works fine. So the issue seems to do with auto-completion.

> 3. what happens if you start cmd.exe, cd to X:\somedir, then start PyCmd.exe straight from the command prompt?

Works, as long as it does not try to auto-complete

> 4. what happens if you start some python3 interpreter, then os.chdir('X:\somedir'), then try to do a pathlib.Path().glob('*')?

No hangs, but does not list the directories or files within. Log below:

```
>python --version
Python 3.12.6
>python
Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import pathlib
>>> os.chdir('M:\\')
>>> os.getcwd()
'M:\\'
>>> pathlib.Path().glob('*')
<generator object Path.glob at 0x000001FA62D09470>
```

**Comment by horeah** [comment] 2024-10-27 20:18
> I would be very happy to help to have this resolved.

Appreciated!

> Works, as long as it does not try to auto-complete

This is already interesting (read: surprising) -- normally, while you type the auto-suggestion mechanism kicks-in and tries to suggest a continuation to the typed text based on the file listing (using the same mechanism that the Tab-completion uses). 

> No hangs, but does not list the directories or files within. Log below:

My bad, sorry for being sloppy: `glob()` returns a generator object so in order to actually iterate over the files you need to execute `list(pathlib.Path().glob('*'))`. 
While you are at it, please also try `os.listdir()` after `os.chdir()` in the `M:\\` directory, and maybe also `os.listdir('M:\\')` after `chdir('C:\\somewhere')`

**Comment by jay-ramani** [comment] 2024-10-30 01:27
> This is already interesting (read: surprising) -- normally, while you type the auto-suggestion mechanism kicks-in and tries to suggest a continuation to the typed text based on the file listing (using the same mechanism that the Tab-completion uses).

Yup, hangs when the auto-suggestion kicks in

> 
> > No hangs, but does not list the directories or files within. Log below:
> 
> My bad, sorry for being sloppy: `glob()` returns a generator object so in order to actually iterate over the files you need to execute `list(pathlib.Path().glob('*'))`. While you are at it, please also try `os.listdir()` after `os.chdir()` in the `M:\\` directory, and maybe also `os.listdir('M:\\')` after `chdir('C:\\somewhere')`

Both `list(pathlib.Path().glob('*'))` and `os.listdir('M:\\')` list the entries fine

**Comment by jay-ramani** [comment] 2024-11-12 00:16
Do you need anything else to help with the fix?

**Comment by horeah** [comment] 2024-11-12 21:53
I could really use a way to reproduce this on my side somehow -- but I have no idea how, right now.

In the meanwhile, I started looking into adding a timeout mechanism to the completion/suggestion function; while investigating, I realized that the performance of the completion/suggestion code can be easily improved with a few simple changes, so I went ahead and implemented that instead :|

The speed improvements can be felt everywhere, but are especially visible on "slow" filesystems (such as network drives); so it might make sense for you to try them out -- although I am only half-optimistic that this will help with your particular problem.

If you are willing to give this a spin, please download this build: [PyCmd-20241112-w64.zip](https://github.com/user-attachments/files/17723186/PyCmd-20241112-w64.zip)

**Comment by jay-ramani** [comment] 2024-11-13 03:52
> I could really use a way to reproduce this on my side somehow -- but I have no idea how, right now.
> 
> In the meanwhile, I started looking into adding a timeout mechanism to the completion/suggestion function; while investigating, I realized that the performance of the completion/suggestion code can be easily improved with a few simple changes, so I went ahead and implemented that instead :|
> 
> The speed improvements can be felt everywhere, but are especially visible on "slow" filesystems (such as network drives); so it might make sense for you to try them out -- although I am only half-optimistic that this will help with your particular problem.
> 
> If you are willing to give this a spin, please download this build: [PyCmd-20241112-w64.zip](https://github.com/user-attachments/files/17723186/PyCmd-20241112-w64.zip)

This build works! Woohoo!

**Comment by horeah** [comment] 2024-11-22 20:25
> This build works! Woohoo! Great job.

Good news! Thanks for reporting and investigating this. The change will be part of the next release (to be published soon).

> Btw, love your formatting and structure of the readme.md of this project.

I am not sure if this is meant as a compliment, or sarcasm 😆 Either way is fine, because I am half proud and half ashamed of the "ridiculously spartan" style of the README...

**Closed by horeah** 2024-11-22 20:25 UTC

**Comment by jay-ramani** [comment] 2024-11-22 20:45
> > Btw, love your formatting and structure of the readme.md of this project.
> 
> I am not sure if this is meant as a compliment, or sarcasm 😆 Either way is fine, because I am half proud and half ashamed of the "ridiculously spartan" style of the README...

Huh! It's definitely a compliment - I loved the simple, yet structured format. Not sure why you thought it was sarcasm.

**Comment by horeah** [comment] 2024-11-22 21:15
> Huh! It's definitely a compliment - I loved the simple, yet structured format. Not sure why you thought it was sarcasm.

I sometimes worry that this kind of "frugal" format gives an outdated feel... Good to know people still appreciate it ;)
